### ISSUE TITLE
jp plugin doesn't support umd

### ISSUE THREAD

**Issue by yoshidax** [MihaiValentin/lunr-languages#26]
Since `/tinyseg.js` related to Japanese plugin does not support umd, it can not be used with node.js or require.js.

I fixed this problem, so I will pull the request. 😃

**Comment by MihaiValentin** [comment]
Thanks for the MR.

One question though. Does Japanese language support stemming? I noticed you added a TODO for the stemmer.

Please let me know so I can update my readme file accordingly.

Thanks!

**Comment by yoshidax** [comment]
@MihaiValentin

I have not added [TODO](https://github.com/MihaiValentin/lunr-languages/blame/master/lunr.jp.js#L93), but as far as I confirm, the Japanese stemmer implementation of JavaScript does not seem to exist.

Still, Japanese plugins work as smoothly as it is. 😊

Tokenizer may be playing the role of stemmer, but I am not an expert on natural language processing, so I do not know the details.

I think that TODO comments should be deleted.

**Comment by MihaiValentin** [comment]
@yoshidax, thanks for the input!

I am glad the Japanese plugin works smooth and I'll keep it like this for now.
