### ISSUE TITLE
lunr.de demo with unexpected result for umlauts

### ISSUE THREAD

**Issue by derplakatankleber** [MihaiValentin/lunr-languages#41]
I tried your demosite "demo-browser-require.html", but I don't understand the results.

tests:
console.log('Search for `günstige`: ', idx.search('günstige'));// expected resultsize: 1, result: 1
console.log('Search for `günstig*`: ', idx.search('günstig\*'));// **expected resultsize: 1, result: 0**
console.log('Search for `g*nstig*`: ', idx.search('g\*nstig\*'));// expected resultsize: 1, result: 1

source: https://rawgit.com/MihaiValentin/lunr-languages/master/demos/demo-browser-require.html

Did I missunderstood, how to search for words with umlauts, or is it not possible to search with wildcards for words with umlauts?

**Comment by khawkins98** [comment]
I also noticed this. 

In #66 the approach of replacing:

> lunr.de.wordCharacters = "A-Za-züÜÄäÖöß0-9";

Fixes wildcard support.

**Comment by khawkins98** [comment]
I also wound up changing approaches. I can dig up my code, but I believe what I did was:

1. Convert the umlaut character to their `ae`, `ue` versions
2. Do the same for the passed search string
