### ISSUE TITLE
Fix Dutch language code

### ISSUE THREAD

**Issue by larsgw** [MihaiValentin/lunr-languages#43]
I believe the language code for Dutch should be `nl` and not `du` according to [ISO 639-1](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=nl), which is the standard linked to in the [Language Support](https://lunrjs.com/guides/language_support.html) guide of lunr.

**Comment by MihaiValentin** [comment]
Fixed, closing the issue.
