### ISSUE TITLE
When will the lunr languages version be compatible with lunrjs v.2.3.5?

### ISSUE THREAD

**Issue by rludgero** [MihaiValentin/lunr-languages#48]
Hi, when will the lunr languages version be compatible with lunrjs v.2.3.5?

Do you have plans to update it soon?

Thanks.

**Comment by MihaiValentin** [comment]
Hi @rludgero, I have just ran the tests against v2.3.5 and the tests passed. Did you experience any issues?

**Comment by rludgero** [comment]
Hi @MihaiValentin, no, I have not come to prove it, since I've seen that in the **Readme**.

> "Lunr Languages is compatible with Lunr version 0.6, 0.7, 1.0 and 2.0 (latest alpha)."

I'm going to try and if everything works ok, I close the issue.

**Comment by rludgero** [comment]
I just tried and everything works ok 👌 

- **lunr.js v.2.3.5**, 
- **lunr.stemmer.support.js last version**,
- **lunr.es.js last version**.

It would be nice to update the readme. 

Regards
