### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by mrmlnc** [MihaiValentin/lunr-languages#5]
Please add this repository in the [Bower](http://bower.io/). This will help save time during development.

**Comment by JSteunou** [comment]
+1 for this one. Lunr is meant for browsers, and on browsers side, we are using bower a loooooooot!

Pretty please :)

**Comment by MihaiValentin** [comment]
Added to bower. Enjoy!

**Comment by JSteunou** [comment]
Thank you @MihaiValentin !
