### ISSUE TITLE
Minified version of the Thai language is missing

### ISSUE THREAD

**Issue by pinmu** [MihaiValentin/lunr-languages#70]
https://github.com/MihaiValentin/lunr-languages/tree/master/min

From above link, there is no Thai.  It seems lunr.th.min.js is missing.

Best regards,

**Comment by bird50** [comment]
> https://github.com/MihaiValentin/lunr-languages/tree/master/min
> 
> From above link, there is no Thai. It seems lunr.th.min.js is missing.
> 
> Best regards,

No Thai-lang but not min

**Comment by MihaiValentin** [comment]
Fixed, the minified Thai file is now part of the package.
